service: serverless-framework-latest-sentry-lambda-layer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:us-east-1:943013980633:layer:SentryNodeServerlessSDK:latest

plugins:
  - serverless-latest-layer-version
    